spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/easyeats
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    locations:
      - classpath:db/migration
    baselineOnMigrate: true

server:
  port: 8081

logging:
  level:
    com:
      sorsix:
        finalproject:
          easyeats: DEBUG